export const enum Tags {
  Animals = "Animals",
  CriminalJustice = "Criminial Justice",
  Disability = "Disability",
  EconomicJustice = "Economic Justice",
  Education = "Education",
  Entertainment = "Entertainment",
  Environment = "Environment",
  Family = "Family",
  Food = "Food",
  Health = "Health",
  HumanRights = "Human Rights",
  Immigration = "Immigration",
  LGBTRights = "LGBT Rights",
  Politics = "Politics",
  Technology = "Technology",
  WomensRights = "Women's Rights",
}

export const TagsArray: Tags[] = [
  Tags.Animals,
  Tags.CriminalJustice,
  Tags.Disability,
  Tags.EconomicJustice,
  Tags.Education,
  Tags.Entertainment,
  Tags.Environment,
  Tags.Family,
  Tags.Food,
  Tags.Health,
  Tags.HumanRights,
  Tags.Immigration,
  Tags.LGBTRights,
  Tags.Politics,
  Tags.Technology,
  Tags.WomensRights,
];
