export const enum Tags {
  Animals = "Animals",
  Education = "Education",
  Environment = "Environment",
  Transport = "Transport",
  Food = "Food",
  Plastic = "Plastic",
  Habitat = "Habitat",
  Sanctuary = "Sanctuary",
  Wildlife = "Wildlife",
  Sustainability = "Sustainability",
  Recycling = "Recycling",
  Health = "Health",
  Plantation = "Plantation",
  Water = "Water",
  Technology = "Technology",
  WomensRights = "Women's Rights",
}

export const TagsArray: Tags[] = [
  Tags.Animals,
  Tags.Education,
  Tags.Environment,
  Tags.Food,
  Tags.Health,
  Tags.Technology,
  Tags.WomensRights,
  Tags.Plantation,
  Tags.Plastic,
  Tags.Recycling,
  Tags.Sanctuary,
  Tags.Sustainability,
  Tags.Transport,
  Tags.Water,
  Tags.Wildlife,
  Tags.Habitat,
];
